name: CI/CD Pipeline Backend a AWS EC2 via ECR

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    name: Build y Push de la Imagen a ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 

      - name: Iniciar sesión en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, y push de la imagen Docker a ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backendventasinnovatech 
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-ec2:
    name: Despliegue en EC2 (Backend Privado)
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar despliegue automático vía Bastion/Frontend
        uses: appleboy/ssh-action@master
        with:
         
          host: ${{ secrets.BACKEND_PRIVATE_IP }} 
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          
         
          proxy_host: ${{ secrets.FRONTEND_PUBLIC_IP }} 
          proxy_username: ${{ secrets.EC2_USER }}
          proxy_key: ${{ secrets.AWS_PRIVATE_KEY }}
          
          script: |
            # Autenticar en ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
            
            # Limpiar contenedor anterior
            docker stop app-backend || true
            docker rm app-backend || true
            
            # Descargar nueva imagen
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backendventasinnovatech:latest
            
            # Levantar el contenedor del backend (Ajustado al puerto 8080 de Spring Boot)
            docker run -d --name app-backend -p 8080:8080 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backendventasinnovatech:latest
